=== MegaZ35/LIBRARY/library/books.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (magazines, users)>
<!ELEMENT magazines (magazine+)>
<!ELEMENT magazine (title, number, year+, editorial, article, state)>
<!ELEMENT users (user+)>
<!ELEMENT user (name+, direction, phones+, gmail?, tipe, loan)>
<!ATTLIST book name CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED>
<!ATTLIST book editorial CDATA #REQUIRED>
<!ATTLIST book year CDATA #REQUIRED>
<!ATTLIST book gender CDATA #REQUIRED>
<!ATTLIST book location CDATA #REQUIRED>
<!ATTLIST article author CDATA #REQUIRED>
<!ATTLIST article title  CDATA #REQUIRED>
<!ATTLIST article page  CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT article (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT direction (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT gmail (#PCDATA)>
<!ELEMENT tipe (#PCDATA)>
<!ELEMENT loan (#PCDATA)>
<!ELEMENT phones (phone+)>

=== MegaZ35/LIBRARY/library/books.xml
<!DOCTYPE books SYSTEM "books.dtd">
<books>
    <book name="J.K. Rowling" title="" editorial="Bloomsbury" year="1997" gender="Fantasia" location="Londres">
        <magazines>
            <magazine>
                <title>Magazine 2</title>
                <number>30</number>
                <year>1997</year>
                <editorial>Bloomsbury</editorial>
                <article author="Author1" title="Articulo1" page="6"></article>
                <state>disponible</state>
            </magazine>
        </magazines>
        <users>
            <user>
                <name>Bector</name>
                <direction>Calle las torres</direction>
                <phones>
                    <phone>12589647</phone>
                </phones>
                <gmail>bector@gmail.com</gmail>
                <tipe>estudiante</tipe>
                <loan>Harry Potter</loan>
            </user>
        </users>
    </book>



    <book name="J.R.R. Tolkien" title="El SeÃ±or de los Anillos" editorial="Allen y Unwin" year="1954" gender="Fansatia" location="Reino Unido">
        <magazines>
            <magazine>
                <title>Political Review</title>
                <number>10</number>
                <year>1950</year>
                <editorial>Allen Y Unwin</editorial>
                <article author="C. Lewis" title="La sociedad del control" page="9"></article>
                <state>disponible</state>
            </magazine>

        </magazines>
        <users>
            <user>
                <name>Manolo</name>
                <direction>Calle velgica</direction>
                <phones>
                    <phone>25697425</phone>
                </phones>
                <tipe>general</tipe>
                <loan>1984</loan>
            </user>
        </users>
    </book>
</books>
